Issue multiple warp sync requests in grandpa warp sync if needed
paritytech/smoldot pull request #468
Opened 2021-02-05 15:19 UTC by expenses

2021-02-05 15:21 UTC, tomaka commented
Instead of a hardcoded limit of 100, is it not possible to continue issuing requests until it comes back empty?

2021-02-05 15:23 UTC, expenses commented
> Instead of a hardcoded limit of 100, is it not possible to continue issuing requests until it comes back empty?

I'm not sure, it might be that the minimum number of requests returned is 1. I would much rather send the fragments along with a boolean that indicates whether more requests need to be made or not though.

2021-02-05 15:27 UTC, tomaka commented
The boolean would indeed remove a round trip time.

> I'm not sure, it might be that the minimum number of requests returned is 1.

Note that we must be resilient to that kind of thing if the Substrate node misbehaves (intentionally or not). Smoldot shouldn't be trapped in an infinite loop, whatever what is received is.

2021-02-05 16:09 UTC, expenses commented
>  I'm not sure, it might be that the minimum number of requests returned is 1.

I just confirmed this by setting `let final_set_of_fragments = response_fragments.len() == 1;`.

> Note that we must be resilient to that kind of thing if the Substrate node misbehaves (intentionally or not). Smoldot shouldn't be trapped in an infinite loop, whatever what is received is.

I think that having the check above would eliminate most problems.

2021-02-05 16:19 UTC, tomaka commented
Is it not possible for the target Substrate node to randomly generate one Grandpa warp sync fragment (with a different random hash every time) and block smoldot forever?

2021-02-05 16:43 UTC, expenses commented
> Is it not possible for the target Substrate node to randomly generate one Grandpa warp sync fragment (with a different random hash every time) and block smoldot forever?

I don't think verification would succeed in this case. And as `final_set_of_fragments` would be true, we would only attempt to validate once. What _might_ block smoldot is if a node sent the same (valid) fragment 100 times. I'm not sure what happens with verification then.

2021-02-05 16:48 UTC, tomaka commented
Right, sorry. I somehow had in my mind that we were downloading everything first, and then only start the verification.

2021-02-08 08:56 UTC, tomaka requested changes
Good after removing the extra copies

2021-02-08 08:56 UTC, tomaka commented on src/chain/sync/grandpa_warp_sync.rs
> +    }
Let's please not just copy things all the time.

```suggestion
    pub fn warp_sync_header(&self) -> HeaderRef {
        (&self.state.header).into()
    }
```

2021-02-08 08:56 UTC, tomaka commented on src/chain/sync/grandpa_warp_sync.rs
> +    }
Same

2021-02-08 08:56 UTC, tomaka commented on src/chain/sync/grandpa_warp_sync.rs
> +    }
Ditto

2021-02-08 08:56 UTC, tomaka commented on src/finality/grandpa/warp_sync.rs
> +        start_chain_information_finality: &ChainInformationFinality,
```suggestion
        start_chain_information_finality: ChainInformationFinalityRef,
```

2021-02-08 09:16 UTC, tomaka approved these changes

2021-02-08 09:47 UTC, merged